# This file is generated by the PHP Server Control Panel — do not edit it by hand
# An edit is overwritten the next time a mailbox changes through the web page
#
# Generated at: {{GENERATED_AT}}
#
# Named starting with 99- so it's read after every one of the distro's own
# files — a value set here therefore always wins over the default, with no need to edit the package's own file, which gets overwritten on upgrade

# No unencrypted imap/pop3 — a mail password travels over the network every
# time a mail client checks the mailbox (every few minutes) · leaving 110/143 open means announcing the password to the whole network
protocols = imap pop3 lmtp
ssl = required

# The mail hostname's certificate — **must also be set here, not only at Postfix**
#
# A mail client connects IMAP/POP3 directly to Dovecot (993/995), never
# through Postfix at all · setting the real certificate for Postfix alone
# gets a machine that "sends mail with no warning, but opening the mailbox
# always shows a certificate warning" — a symptom that's especially hard to
# diagnose, since half the system is working correctly
#
# The leading `<` is Dovecot's own syntax meaning "read the content from this file," not part of the path
ssl_cert = <{{TLS_CERT}}
ssl_key = <{{TLS_KEY}}

service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 0
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

# Where mailboxes are stored — every mailbox belongs to the single vmail user, never one system user per mailbox
# %d = domain · %n = the part before @ (Dovecot substitutes these itself)
mail_home = {{MAIL_ROOT}}/%d/%n
mail_location = maildir:~/
mail_uid = {{VMAIL_USER}}
mail_gid = {{VMAIL_USER}}

# Creates the standard folders from the very first login, instead of waiting
# for a mail client to create them itself (different clients name them differently, and you'd end up with two differently-named "Sent" folders)
namespace inbox {
  inbox = yes

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
}

# Users come from a file the panel writes, never from the machine's own /etc/passwd
passdb {
  driver = passwd-file
  args = scheme=ARGON2ID username_format=%u {{USERS_FILE}}
}

userdb {
  driver = passwd-file
  args = username_format=%u {{USERS_FILE}}
}

# Per-mailbox quota — the real value comes from the per-user line in the users file (userdb_quota_rule)
#
# **Must refuse at delivery, never accept then discard** — if the mailbox is
# full and mail is still accepted then thrown away, the sender believes it
# was delivered, which is far worse than being refused from the start
plugin {
  quota = maildir:User quota
  quota_rule = *:storage=1G
  quota_grace = 0%%
}

protocol lmtp {
  mail_plugins = $mail_plugins quota
  # Postfix sends the full address — never strip the domain, or a same-named mailbox in a different domain would collide
  auth_username_format = %u
}

protocol imap {
  mail_plugins = $mail_plugins quota imap_quota
}

# Postfix talks to Dovecot through two sockets: delivering mail into a mailbox (lmtp), and asking for a password (auth)
service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

# ---------------------------------------------------------------------------
# The admin's own additional settings — read last, so a value there always wins over anything above
#
# `!include_try` never fails when the file doesn't exist yet, unlike
# `!include`, which would keep Dovecot from starting entirely · the panel never overwrites any file in this directory
# ---------------------------------------------------------------------------
!include_try {{CUSTOM_DIR}}/*.conf
