<?php

declare(strict_types=1);

namespace Phpcp\Domain;

use Phpcp\Agent\ValidationError;
use Phpcp\Driver\WebServer\CustomConfig;

/**
 * ทะเบียนไฟล์ตั้งค่าที่เปิดให้ดูและแก้จากหน้าเว็บ — allowlist ตายตัวแบบเดียวกับ capability
 *
 * ## กติกาข้อเดียวที่ทำให้ทั้งเรื่องปลอดภัย
 *
 * **หน้าจออ้างไฟล์ด้วย "คีย์" ไม่ใช่ "เส้นทาง"** · เส้นทางจริงถูกประกอบที่นี่จากข้อมูล
 * ที่ผ่านการตรวจแล้วเท่านั้น ผู้เรียกจึงไม่มีทางขอไฟล์นอกทะเบียนได้เลย ต่อให้ส่งคีย์
 * อะไรมาก็ตาม — ต่างจากการรับเส้นทางมาแล้วค่อยตรวจ ซึ่งต้องคิดให้ครบทุกรูปแบบการหลบ
 * (`..`, symlink, unicode, เส้นทางสัมพัทธ์) และพลาดข้อเดียวก็อ่านไฟล์ไหนบนเครื่องก็ได้
 *
 * ## แก้ได้กับดูได้ ต้องแยกกันให้ชัดตั้งแต่ชั้นข้อมูล
 *
 * ไฟล์ที่ panel สร้างเปิดดูได้แต่แก้ไม่ได้ **โดยตั้งใจ** — มันถูกเขียนทับทั้งไฟล์ทุกครั้ง
 * ที่มีคนแตะข้อมูลที่เกี่ยวข้อง การเปิดให้แก้คือการสร้างกับดัก "แก้แล้วใช้ได้ แล้ววันหนึ่ง
 * หายไปเงียบ ๆ" · `writable` จึงเป็นข้อมูลที่มาจากเซิร์ฟเวอร์ ไม่ใช่การตัดสินใจของหน้าจอ
 */
final class ConfigFileCatalog
{
    public const KIND_WRITABLE = 'writable';
    public const KIND_GENERATED = 'generated';

    /**
     * ไฟล์ทั้งหมดของเว็บไซต์หนึ่ง
     *
     * @param list<string> $vhostPaths ไฟล์ที่เว็บเซิร์ฟเวอร์ตัวปัจจุบันสร้างให้เว็บนี้
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forSite(int $siteId, string $domain, string $server, array $vhostPaths): array
    {
        $custom = $server === 'nginx' ? 'nginx' : 'apache';

        $files = [[
            'key' => sprintf('site.%d.custom', $siteId),
            'label' => 'Extra configuration (yours)',
            'path' => CustomConfig::sitePath($custom, $domain),
            'kind' => self::KIND_WRITABLE,
            'service' => $custom,
        ]];

        foreach (array_values($vhostPaths) as $index => $path) {
            $files[] = [
                'key' => sprintf('site.%d.vhost.%d', $siteId, $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                'service' => $custom,
            ];
        }

        return $files;
    }

    /**
     * ไฟล์ของระบบเมล — เป็นของทั้งเครื่อง ไม่ผูกกับเว็บไซต์ใด
     *
     * @param list<string> $generated ไฟล์ที่ panel สร้างให้เมล (main.cf · 99-phpcp.conf)
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forMail(array $generated = []): array
    {
        $files = [
            [
                'key' => 'mail.postfix.custom',
                'label' => 'Postfix — extra configuration (yours)',
                'path' => CustomConfig::servicePath('postfix'),
                'kind' => self::KIND_WRITABLE,
                'service' => 'postfix',
            ],
            [
                'key' => 'mail.dovecot.custom',
                'label' => 'Dovecot — extra configuration (yours)',
                'path' => CustomConfig::servicePath('dovecot'),
                'kind' => self::KIND_WRITABLE,
                'service' => 'dovecot',
            ],
        ];

        foreach (array_values($generated) as $index => $path) {
            $files[] = [
                'key' => sprintf('mail.generated.%d', $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                // ไฟล์ที่ระบบสร้างไม่มีบริการปลายทางให้เขียน จึงไม่ต้องระบุ
                'service' => '',
            ];
        }

        return $files;
    }

    /**
     * ไฟล์ของ BIND9 — เป็นของทั้งเครื่อง ไม่ผูกกับโดเมนใด
     *
     * zone ของแต่ละโดเมนไม่อยู่ในทะเบียนนี้โดยตั้งใจ — มันเป็นข้อมูลของโดเมนนั้น ๆ และมี
     * หน้าจอของตัวเองอยู่แล้วในหน้าโดเมน · ที่นี่คือไฟล์ระดับเครื่องที่กระทบทุกโดเมนพร้อมกัน
     *
     * **เส้นทางของไฟล์ที่แก้ได้ถูกส่งเข้ามา ไม่ได้ประกอบที่นี่** — มันอิงกับที่อยู่ของ
     * `named.conf.local` ซึ่งตั้งค่าได้ และอยู่คนละรากกับไฟล์ส่วนเสริมของบริการอื่น
     * ด้วยเหตุผลเรื่องสิทธิ์การอ่านของ named ({@see CustomConfig::SEEDS})
     *
     * @param string $customPath ไฟล์ส่วนเสริมของผู้ดูแล
     * @param list<string> $generated ไฟล์ที่ panel สร้างให้ BIND (named.conf.local)
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forDns(string $customPath, array $generated = []): array
    {
        $files = [[
            'key' => 'dns.bind.custom',
            'label' => 'BIND9 — extra configuration (yours)',
            'path' => $customPath,
            'kind' => self::KIND_WRITABLE,
            'service' => 'bind',
        ]];

        foreach (array_values($generated) as $index => $path) {
            $files[] = [
                'key' => sprintf('dns.generated.%d', $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                'service' => '',
            ];
        }

        return $files;
    }

    /**
     * หาไฟล์จากคีย์ — คืน null เมื่อไม่มีในทะเบียน
     *
     * @param list<array<string,mixed>> $files
     * @return array<string,mixed>|null
     */
    public static function find(array $files, string $key): ?array
    {
        foreach ($files as $file) {
            if ($file['key'] === $key) {
                return $file;
            }
        }

        return null;
    }

    /**
     * รูปแบบคีย์ที่ยอมรับ — ด่านแรกก่อนเอาไปค้นในทะเบียน
     *
     * ไม่ได้กันอะไรด้วยตัวเองเพราะการค้นในทะเบียนกันอยู่แล้ว แต่ทำให้คีย์แปลกปลอม
     * ถูกปฏิเสธด้วยข้อความที่ตรงเรื่อง แทนที่จะไปโผล่เป็น "ไม่พบไฟล์" ซึ่งอ่านแล้ว
     * เข้าใจผิดว่าไฟล์หายไปจากเครื่อง
     */
    public static function assertKey(string $key): string
    {
        if (preg_match('/^[a-z0-9]+(\.[a-z0-9]+)*$/i', $key) !== 1 || strlen($key) > 100) {
            throw new ValidationError('รหัสไฟล์ตั้งค่าไม่ถูกต้อง');
        }

        return $key;
    }
}
