<?php

declare(strict_types=1);

namespace Phpcp\Domain;

use Phpcp\Agent\ValidationError;
use Phpcp\Driver\WebServer\CustomConfig;

/**
 * The registry of config files open for viewing and editing from the web page — a
 * hardcoded allowlist, same as a capability
 *
 * ## The one rule that makes all of this safe
 *
 * **The screen refers to a file by a "key," never a "path"** · the real path is
 * built here, only from data that's already been validated, so a caller has no way
 * to request a file outside this registry no matter what key they send — unlike
 * accepting a path and validating it afterward, which requires accounting for every
 * way to escape it (`..`, symlinks, unicode, relative paths), and missing even one
 * lets any file on the machine be read.
 *
 * ## Editable vs. viewable must be kept clearly separate, starting at the data layer
 *
 * A file the panel generated can be viewed but never edited, **deliberately** — it
 * gets fully overwritten every time someone touches the related data. Allowing an
 * edit would set up exactly the trap of "the edit works, then one day it silently
 * disappears" · `writable` is therefore information that comes from the server, not
 * a decision the screen gets to make.
 */
final class ConfigFileCatalog
{
    public const KIND_WRITABLE = 'writable';
    public const KIND_GENERATED = 'generated';

    /**
     * Every file belonging to one site
     *
     * @param list<string> $vhostPaths files the currently active web server generated for this site
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forSite(int $siteId, string $domain, string $server, array $vhostPaths): array
    {
        $custom = $server === 'nginx' ? 'nginx' : 'apache';

        $files = [[
            'key' => sprintf('site.%d.custom', $siteId),
            'label' => 'Extra configuration (yours)',
            'path' => CustomConfig::sitePath($custom, $domain),
            'kind' => self::KIND_WRITABLE,
            'service' => $custom,
        ]];

        foreach (array_values($vhostPaths) as $index => $path) {
            $files[] = [
                'key' => sprintf('site.%d.vhost.%d', $siteId, $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                'service' => $custom,
            ];
        }

        return $files;
    }

    /**
     * The mail system's files — belong to the whole machine, not tied to any one site
     *
     * @param list<string> $generated files the panel generated for mail (main.cf · 99-phpcp.conf)
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forMail(array $generated = []): array
    {
        $files = [
            [
                'key' => 'mail.postfix.custom',
                'label' => 'Postfix — extra configuration (yours)',
                'path' => CustomConfig::servicePath('postfix'),
                'kind' => self::KIND_WRITABLE,
                'service' => 'postfix',
            ],
            [
                'key' => 'mail.dovecot.custom',
                'label' => 'Dovecot — extra configuration (yours)',
                'path' => CustomConfig::servicePath('dovecot'),
                'kind' => self::KIND_WRITABLE,
                'service' => 'dovecot',
            ],
        ];

        foreach (array_values($generated) as $index => $path) {
            $files[] = [
                'key' => sprintf('mail.generated.%d', $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                // A system-generated file has no destination service to write to, so none is specified
                'service' => '',
            ];
        }

        return $files;
    }

    /**
     * BIND9's files — belong to the whole machine, not tied to any one domain
     *
     * Each domain's zone is deliberately not in this registry — it's that domain's
     * own data and already has its own screen on the domain page · this covers
     * machine-level files that affect every domain at once.
     *
     * **The editable file's path is passed in, not built here** — it's based on
     * where `named.conf.local` lives, which is configurable, and sits under a
     * different root than other services' supplementary files, for reasons tied to
     * what `named` is permitted to read ({@see CustomConfig::SEEDS}).
     *
     * @param string $customPath the admin's supplementary file
     * @param list<string> $generated files the panel generated for BIND (named.conf.local)
     * @return list<array{key:string,label:string,path:string,kind:string,service:string}>
     */
    public static function forDns(string $customPath, array $generated = []): array
    {
        $files = [[
            'key' => 'dns.bind.custom',
            'label' => 'BIND9 — extra configuration (yours)',
            'path' => $customPath,
            'kind' => self::KIND_WRITABLE,
            'service' => 'bind',
        ]];

        foreach (array_values($generated) as $index => $path) {
            $files[] = [
                'key' => sprintf('dns.generated.%d', $index),
                'label' => 'Generated by the panel',
                'path' => $path,
                'kind' => self::KIND_GENERATED,
                'service' => '',
            ];
        }

        return $files;
    }

    /**
     * Find a file by its key — returns null when it isn't in the registry
     *
     * @param list<array<string,mixed>> $files
     * @return array<string,mixed>|null
     */
    public static function find(array $files, string $key): ?array
    {
        foreach ($files as $file) {
            if ($file['key'] === $key) {
                return $file;
            }
        }

        return null;
    }

    /**
     * The accepted key shape — the first guard before searching the registry
     *
     * Doesn't guard anything on its own, since the registry lookup already does,
     * but it makes a malformed key get rejected with a message that matches the
     * actual problem, instead of surfacing as "file not found," which reads like
     * the file went missing from the machine.
     */
    public static function assertKey(string $key): string
    {
        if (preg_match('/^[a-z0-9]+(\.[a-z0-9]+)*$/i', $key) !== 1 || strlen($key) > 100) {
            throw new ValidationError('Invalid config file key');
        }

        return $key;
    }
}
