# This file is generated by the PHP Server Control Panel installer — do not edit it by hand
#
# The panel's own Apache instance (ARCHITECTURE §5.2)
# Uses the same binary as the system's, but a separate config tree, a
# separate pid, and a separate port — so it never reads anything from
# /etc/apache2 at all, and never goes down when a user stops apache2.service
#
# Loads modules one by one itself, since it doesn't use the system's own
# mods-enabled — if a user disables a system module through the web page,
# the panel must never be affected by it

ServerRoot        {{CONF_DIR}}/httpd
DefaultRuntimeDir {{RUN_DIR}}
PidFile           {{RUN_DIR}}/panel-httpd.pid
Mutex             file:{{RUN_DIR}} default

ServerName      {{PANEL_HOST}}
ServerAdmin     root@localhost
ServerTokens    Prod
ServerSignature Off
TraceEnable     Off

Timeout              60
KeepAlive            On
MaxKeepAliveRequests 100
KeepAliveTimeout     5

# ---------------------------------------------------------------------------
# Modules — only what the panel genuinely uses
# Wrapped in <IfModule !x>, since some distros compile a module directly into
# the binary already (Debian's unixd, for example) — loading it again would make apache2 refuse to start
# ---------------------------------------------------------------------------
<IfModule !mpm_event_module>
    LoadModule mpm_event_module {{MODULES_DIR}}/mod_mpm_event.so
</IfModule>
<IfModule !unixd_module>
    LoadModule unixd_module {{MODULES_DIR}}/mod_unixd.so
</IfModule>
<IfModule !authz_core_module>
    LoadModule authz_core_module {{MODULES_DIR}}/mod_authz_core.so
</IfModule>
<IfModule !log_config_module>
    LoadModule log_config_module {{MODULES_DIR}}/mod_log_config.so
</IfModule>
<IfModule !mime_module>
    LoadModule mime_module {{MODULES_DIR}}/mod_mime.so
</IfModule>
<IfModule !dir_module>
    LoadModule dir_module {{MODULES_DIR}}/mod_dir.so
</IfModule>
<IfModule !headers_module>
    LoadModule headers_module {{MODULES_DIR}}/mod_headers.so
</IfModule>
<IfModule !filter_module>
    LoadModule filter_module {{MODULES_DIR}}/mod_filter.so
</IfModule>
<IfModule !deflate_module>
    LoadModule deflate_module {{MODULES_DIR}}/mod_deflate.so
</IfModule>
<IfModule !reqtimeout_module>
    LoadModule reqtimeout_module {{MODULES_DIR}}/mod_reqtimeout.so
</IfModule>
<IfModule !proxy_module>
    LoadModule proxy_module {{MODULES_DIR}}/mod_proxy.so
</IfModule>
<IfModule !proxy_fcgi_module>
    LoadModule proxy_fcgi_module {{MODULES_DIR}}/mod_proxy_fcgi.so
</IfModule>
<IfModule !socache_shmcb_module>
    LoadModule socache_shmcb_module {{MODULES_DIR}}/mod_socache_shmcb.so
</IfModule>
<IfModule !ssl_module>
    LoadModule ssl_module {{MODULES_DIR}}/mod_ssl.so
</IfModule>

# The master starts as root to bind the port and read the certificate, then drops privileges immediately
User  {{PANEL_USER}}
Group {{PANEL_GROUP}}

<IfModule mpm_event_module>
    StartServers           1
    MinSpareThreads        4
    MaxSpareThreads        8
    ThreadsPerChild        16
    MaxRequestWorkers      32
    MaxConnectionsPerChild 0
</IfModule>

# Guards against a worker being held hostage by a slow-drip request (slowloris)
<IfModule reqtimeout_module>
    RequestReadTimeout header=20-40,MinRate=500 body=20,MinRate=500
</IfModule>

# ---------------------------------------------------------------------------
# File types — declared directly, so it never depends on the system's own /etc/mime.types
# ---------------------------------------------------------------------------
<IfFile /etc/mime.types>
    TypesConfig /etc/mime.types
</IfFile>
AddType text/css                  .css
AddType text/javascript           .js
AddType image/svg+xml             .svg
AddType application/json          .json
AddType font/woff2                .woff2
AddDefaultCharset UTF-8

<IfModule deflate_module>
    AddOutputFilterByType DEFLATE text/html text/css text/javascript application/json image/svg+xml
</IfModule>

# ---------------------------------------------------------------------------
# The panel's own log, separate from the system's /var/log/apache2
# ---------------------------------------------------------------------------
ErrorLog  {{LOG_DIR}}/panel-error.log
LogLevel  warn
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog {{LOG_DIR}}/panel-access.log combined

# Closes off the entire filesystem first, then opens only the document root
<Directory />
    Options None
    AllowOverride None
    Require all denied
</Directory>

Listen {{PANEL_PORT}}

<VirtualHost *:{{PANEL_PORT}}>
    DocumentRoot {{INSTALL_DIR}}/public

    SSLEngine on
    SSLCertificateFile    {{CONF_DIR}}/tls/panel.crt
    SSLCertificateKeyFile {{CONF_DIR}}/tls/panel.key
    SSLProtocol         -all +TLSv1.2 +TLSv1.3
    SSLHonorCipherOrder off
    SSLSessionTickets   off
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

    # The body's ceiling — comfortably larger than what the file manager can genuinely send (FileCatalog::MAX_TRANSFER_BYTES)
    LimitRequestBody 33554432

    <Directory {{INSTALL_DIR}}/public>
        Options -Indexes -Includes -ExecCGI +FollowSymLinks
        AllowOverride None
        Require all granted

        # A single front controller per public/index.php — no .htaccess ever needs to be read
        DirectoryIndex index.php
        FallbackResource /index.php
    </Directory>

    # The panel's own PHP only ever goes to the panel's own FPM master, never any website's pool
    <FilesMatch "\.php$">
        SetHandler "proxy:unix:{{RUN_DIR}}/panel-fpm.sock|fcgi://panel"
    </FilesMatch>

    # Sends data out the moment PHP flushes, without waiting for the response to finish
    #
    # mod_proxy_fcgi buffers the entire response by default, which doesn't
    # work with Server-Sent Events at all: `/api/v2/metrics/stream` never
    # ends on its own within 30 minutes, so Apache never sends even the
    # header out — a screen waiting on live values would hang blank with no
    # error to see at all (found by firing a real test, not from the test
    # suite, since tests never travel through Apache)
    <Proxy "unix:{{RUN_DIR}}/panel-fpm.sock|fcgi://panel">
        ProxySet flushpackets=on
    </Proxy>

    # The only files allowed to be processed by PHP are the front controller, Adminer, and phpMyAdmin
    #
    # Uses a single RequireAny — never put "Require all denied" inside it
    # alongside another condition — RequireAll needs every condition to pass
    # at once, but "Require all denied" always refuses by definition, so when
    # it sits inside a RequireAll together with another condition, the whole
    # block always refuses every request, regardless of whether the RequireAny
    # inside it matches or not (this is how every phpMyAdmin file except index.php ended up answering 403)
    #
    # Apache already refuses by default when no Require passes at all, so there's no need for a redundant "Require all denied" on top
    <Files ~ "^(?!index\.php$).*\.php$">
        <RequireAny>
            Require expr "%{REQUEST_URI} =~ m#^/(adminer|phpmyadmin)#"
        </RequireAny>
    </Files>

    <FilesMatch "^\.">
        Require all denied
    </FilesMatch>

    # Every other security header (CSP, HSTS, X-Frame-Options, etc.) is set
    # by Middleware\SecurityHeaders, so there are never two sources that could conflict
    Header always unset X-Powered-By
    Header always unset Server
</VirtualHost>

SSLSessionCache        shmcb:{{RUN_DIR}}/panel-ssl-cache(512000)
SSLSessionCacheTimeout 300
SSLRandomSeed startup file:/dev/urandom 512
SSLRandomSeed connect builtin
