# This file is generated by the PHP Server Control Panel — do not edit it by hand
# An edit is overwritten the next time mail settings change through the web page
#
# Generated at: {{GENERATED_AT}}
#
# This file serves two roles depending on the `hosting` value:
#   Off  Outbound only, never accepts inbound mail from outside at all (every machine's default)
#   On   Also accepts inbound mail into real mailboxes (PLAN-MAIL phase M1)
# See src/Driver/Mail/MailManager.php for the reasoning behind both modes

compatibility_level = 3.6

myhostname = {{HOSTNAME}}
myorigin = {{ORIGIN}}

# **Must also accept mail addressed to the machine's own name, not just localhost**
#
# `myorigin` above makes every piece of mail this machine generates addressed
# as `someone@hostname` (cron output, system messages, a script calling
# sendmail) · if `mydestination` only has `localhost`, that name points back
# at this machine but no line says to accept it, so Postfix answers **"loops
# back to myself"** and the mail sits in the queue until it expires after five days and disappears
#
# Genuinely happened on a real machine (2026-08-13): mail was stuck in the
# queue for this exact reason while everything else was correct · nothing raised a flag until the queue page was opened
#
# This value is left as just `localhost` when the machine's own hostname is
# also used as a mailbox domain — `mydestination` and `virtual_mailbox_domains`
# can never both list the same name, Postfix refuses and stops accepting mail for that domain entirely
mydestination = {{MYDESTINATION}}

# **mynetworks is what prevents this machine from becoming an open relay** —
# trusts only this machine itself, regardless of whether inbound mail is
# accepted · an outside machine that wants to send mail **through** us must always authenticate first (see smtpd_relay_restrictions below)
#
# Widening this value would get the machine used to send spam within a few
# hours, and its IP permanently blacklisted, affecting every website on the same machine
inet_interfaces = {{INET_INTERFACES}}
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128

relayhost = {{RELAY_HOST}}

# Authenticates with the relay provider
smtp_sasl_auth_enable = {{SASL_ENABLED}}
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous

# encrypt = refuses to send if it can't encrypt (safer)
# may     = tries to encrypt first, sends unencrypted if it can't
smtp_tls_security_level = {{TLS_SECURITY}}
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_tls_loglevel = 1

# Never reveals the internal hostname or Postfix's version to the other end
smtpd_banner = $myhostname ESMTP
biff = no
append_dot_mydomain = no
readme_directory = no

# Never lets mail sit in the queue across a whole week — unable to send
# within 1 day means there's a problem that needs fixing, not something to keep waiting on until the queue swells and the disk fills
maximal_queue_lifetime = 1d
bounce_queue_lifetime = 1d

# Maximum mail size 25 MB — most providers already refuse anything larger than this
message_size_limit = 26214400

{{HOSTING_SECTION}}

# ---------------------------------------------------------------------------
# The admin's own additional settings — **placed last, since Postfix uses whichever value was declared later**
#
# Postfix has no include directive for main.cf, so the admin's file content
# is appended here whenever the panel rewrites this file · the source lives
# at /etc/phpcp/custom/postfix/custom.cf, which the panel never overwrites —
# edit that file, never this one, since this entire file is regenerated from scratch every time a mail setting changes
# ---------------------------------------------------------------------------
{{CUSTOM_SECTION}}