<?php

declare(strict_types=1);

namespace Phpcp\Agent\Capability;

use Phpcp\Agent\Capability;
use Phpcp\Agent\Context;
use Phpcp\Agent\Executor\Executor;
use Phpcp\Agent\PermissionDenied;
use Phpcp\Agent\ValidationError;
use Phpcp\Domain\CronSchedule;
use Phpcp\Domain\Site;
use Phpcp\Domain\SiteRepository;
use Phpcp\Security\Permissions;
use Phpcp\Support\Validator;

/**
 * Rewrites a website's cron file entirely from the data in the panel's database
 *
 * Uses the same pattern as a vhost: the panel's database is the source of truth,
 * and the file is generated from it — never edited line by line, since a partial
 * edit lets the file and the database drift apart easily.
 *
 * Security: a cron job runs under the website's own user's privileges, never
 * root — a line in `/etc/cron.d` names the user directly, and a command is
 * checked to contain no newline character, which could inject a new cron job
 * into the file.
 */
final class CronSync implements Capability
{
    /** A website's cron file — named with a phpcp- prefix so it never overwrites an admin's own */
    private const DIR = '/etc/cron.d';

    public static function name(): string
    {
        return 'cron.sync';
    }

    public function permission(): string
    {
        return 'cron.manage';
    }

    public function isMutating(): bool
    {
        return true;
    }

    public function summary(): string
    {
        return 'Rewrite website cron file from system data';
    }

    public function validate(array $args): array
    {
        return ['site_id' => Validator::requireInt($args, 'site_id', 1)];
    }

    public function run(array $args, Executor $executor, Context $context): array
    {
        $repository = new SiteRepository($context->db);
        $site = $repository->load($args['site_id']);

        if ($site === null) {
            throw new ValidationError('The specified website was not found');
        }

        $this->assertOwnership($context, $site->id);

        $jobs = $context->db->all(
            'SELECT * FROM cron_jobs WHERE site_id = :id ORDER BY id',
            ['id' => $site->id],
        );

        $path = self::DIR . '/phpcp-' . $site->domain;
        $enabled = array_values(array_filter($jobs, static fn (array $j): bool => (int) $j['enabled'] === 1));

        if ($enabled === []) {
            // No enabled jobs — better to delete the file than leave an empty one around causing confusion
            $resolved = $executor->path($path);
            if ($executor->exists($resolved)) {
                $executor->removePath($resolved);
            }

            return [
                'site_id' => $site->id,
                'domain' => $site->domain,
                'file' => $path,
                'jobs' => 0,
                'message' => "No enabled automated jobs for {$site->domain} — deleted the cron file",
            ];
        }

        $executor->writeFile($executor->path($path), $this->render($site, $enabled), 0644);

        return [
            'site_id' => $site->id,
            'domain' => $site->domain,
            'file' => $path,
            'jobs' => count($enabled),
            'message' => sprintf('Updated automated jobs for %s (%d job(s))', $site->domain, count($enabled)),
        ];
    }

    /**
     * Builds the cron file's content
     *
     * @param list<array<string,mixed>> $jobs
     */
    private function render(Site $site, array $jobs): string
    {
        $lines = [
            '# This file is generated by the PHP Server Control Panel — do not edit by hand',
            '# Any edit here gets overwritten the next time automated jobs change through the web page',
            '#',
            '# Website: ' . $site->domain,
            '# Generated: ' . date('Y-m-d H:i:s'),
            '',
            'SHELL=/bin/sh',
            'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin',
            '',
        ];

        foreach ($jobs as $job) {
            $schedule = CronSchedule::normalize((string) $job['schedule']);
            $command = self::assertCommand((string) $job['command']);

            $lines[] = '# ' . self::assertComment((string) $job['name']);
            // /etc/cron.d's format differs from a user's own crontab by having a
            // username in the middle, so the job runs under that website's
            // privileges, never root's
            $lines[] = sprintf('%s %s %s', $schedule, $site->systemUser(), $command);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * A command must never contain a newline — otherwise a new cron job could be injected into the file
     *
     * This is the same class of vulnerability as injecting a directive into an
     * Apache config file — only the outcome differs: here it means running any
     * command at all, on a schedule.
     */
    private static function assertCommand(string $command): string
    {
        $command = trim($command);

        if ($command === '') {
            throw new ValidationError('A command to run must be specified');
        }

        if (preg_match('/[\x00-\x1F\x7F]/', $command) === 1) {
            throw new ValidationError('The command contains a disallowed character (a newline or control character)');
        }

        if (mb_strlen($command) > 500) {
            throw new ValidationError('The command exceeds 500 characters');
        }

        // % has a special meaning in crontab (marks stdin) and must be escaped, or the command gets truncated
        return str_replace('%', '\\%', $command);
    }

    private static function assertComment(string $name): string
    {
        return preg_replace('/[\x00-\x1F\x7F]/', '', trim($name)) ?: 'Automated job';
    }

    private function assertOwnership(Context $context, int $siteId): void
    {
        $actor = $context->actor;

        if ($actor->userId === 0
            || in_array($actor->role, [Permissions::SUPERADMIN, Permissions::SYSADMIN], true)) {
            return;
        }

        $owned = (int) $context->db->value(
            'SELECT count(*) FROM sites WHERE id = :id AND owner_user_id = :u',
            ['id' => $siteId, 'u' => $actor->userId],
            0,
        );

        if ($owned === 0) {
            throw new PermissionDenied('You do not have permission to manage this website\'s automated jobs');
        }
    }
}
